//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkMonit.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SilentMode {
            get {
                return ((bool)(this["SilentMode"]));
            }
            set {
                this["SilentMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string DetectHomeOffice {
            get {
                return ((string)(this["DetectHomeOffice"]));
            }
            set {
                this["DetectHomeOffice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("01/26/2017 07:55:00")]
        public global::System.DateTime TimeWorkBegin {
            get {
                return ((global::System.DateTime)(this["TimeWorkBegin"]));
            }
            set {
                this["TimeWorkBegin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("01/26/2017 17:00:00")]
        public global::System.DateTime TimeWorkEnd {
            get {
                return ((global::System.DateTime)(this["TimeWorkEnd"]));
            }
            set {
                this["TimeWorkEnd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("01/26/2017 11:00:00")]
        public global::System.DateTime HOWorkBegin {
            get {
                return ((global::System.DateTime)(this["HOWorkBegin"]));
            }
            set {
                this["HOWorkBegin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("01/26/2017 15:00:00")]
        public global::System.DateTime HOWorkEnd {
            get {
                return ((global::System.DateTime)(this["HOWorkEnd"]));
            }
            set {
                this["HOWorkEnd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Email {
            get {
                return ((string)(this["Email"]));
            }
            set {
                this["Email"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string Signature {
            get {
                return ((string)(this["Signature"]));
            }
            set {
                this["Signature"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Start")]
        public string WrokStartHeader {
            get {
                return ((string)(this["WrokStartHeader"]));
            }
            set {
                this["WrokStartHeader"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("I start work")]
        public string WorkStartBody {
            get {
                return ((string)(this["WorkStartBody"]));
            }
            set {
                this["WorkStartBody"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Stop")]
        public string WorkStopHeader {
            get {
                return ((string)(this["WorkStopHeader"]));
            }
            set {
                this["WorkStopHeader"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("I stop work")]
        public string WorkStopBody {
            get {
                return ((string)(this["WorkStopBody"]));
            }
            set {
                this["WorkStopBody"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Start HO")]
        public string HomeWorkStartHeader {
            get {
                return ((string)(this["HomeWorkStartHeader"]));
            }
            set {
                this["HomeWorkStartHeader"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("I start home office")]
        public string HomeWorkStartBody {
            get {
                return ((string)(this["HomeWorkStartBody"]));
            }
            set {
                this["HomeWorkStartBody"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Stop HO")]
        public string HomeWorkStopHeader {
            get {
                return ((string)(this["HomeWorkStopHeader"]));
            }
            set {
                this["HomeWorkStopHeader"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("I stop home office")]
        public string HomeWorkStopBody {
            get {
                return ((string)(this["HomeWorkStopBody"]));
            }
            set {
                this["HomeWorkStopBody"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dear,")]
        public string MailHeader {
            get {
                return ((string)(this["MailHeader"]));
            }
            set {
                this["MailHeader"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MailPrompt {
            get {
                return ((bool)(this["MailPrompt"]));
            }
            set {
                this["MailPrompt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoHomeWork {
            get {
                return ((bool)(this["AutoHomeWork"]));
            }
            set {
                this["AutoHomeWork"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection HomeOfficeDays {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["HomeOfficeDays"]));
            }
            set {
                this["HomeOfficeDays"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime OnTimeSend {
            get {
                return ((global::System.DateTime)(this["OnTimeSend"]));
            }
            set {
                this["OnTimeSend"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int OnTimeSendType {
            get {
                return ((int)(this["OnTimeSendType"]));
            }
            set {
                this["OnTimeSendType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime OnWorkBeginTime {
            get {
                return ((global::System.DateTime)(this["OnWorkBeginTime"]));
            }
            set {
                this["OnWorkBeginTime"] = value;
            }
        }
    }
}
